version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres

volumes:
  db-data:
    driver: local